apiVersion: v1
kind: Service
metadata:
  name: multi-container-svc-nodeport
  labels:
    app: multi-container-app
spec:
  selector:
    app: multi-container-app
  ports:
  - name: nginx-port
    protocol: TCP
    port: 9001
    targetPort: 80
    nodePort: 30001  # Порт на нодах кластера (диапазон 30000-32767)
  - name: multitool-port
    protocol: TCP
    port: 9002
    targetPort: 8080
    nodePort: 30002  # Порт на нодах кластера (диапазон 30000-32767)
  type: NodePort