apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-https-config
data:
  default.conf: |
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
    
    server {
        listen 443 ssl;
        
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }